version: '3'

includes:
  cargo:
    taskfile: ./mono-dev/task/cargo.yaml
    optional: true
    internal: true

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install txtpp

  install:
    cmds:
      - rm -rf mono-dev
      - git clone https://github.com/Pistonight/mono-dev

  check:
    cmds:
      - task: cargo:clippy-all
      - task: cargo:fmt-check
      - txtpp verify README.md

  fix:
    cmds:
      - task: cargo:fmt-fix
      - txtpp README.md

  test:
    cmds:
      - cargo test
