version: '3'

includes:
  cargo:
    taskfile: ./mono-dev/task/cargo.yaml
    optional: true
    internal: true

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install txtpp

  install:
    - rm -rf mono-dev
    - git clone https://github.com/Pistonight/mono-dev

  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check
    - txtpp verify README.md

  fix:
    - task: cargo:fmt-fix
    - txtpp README.md

  test:
    - cargo test

  upgrade:
    - cargo upgrade

  publish:
    vars:
      VERSION:
        sh: grep -E '^version' Cargo.toml | head -n1 | sed -E 's/^version = "([^"]+)"$/\1/'
    cmds:
      - git tag v{{.VERSION}}
      - git push origin v{{.VERSION}}
      - cargo publish
        
