name: "Workflow Setup"
description: "Workflow Setup"

inputs:
  token:
    description: "GitHub Token"
    required: true
  rust_targets:
    description: "Targets for rust-toolchain"
    default: ""

runs:
  using: composite
  steps:
    - uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ inputs.token }}

    # rust toolchain
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.rust_targets }}
    - uses: Swatinem/rust-cache@v2 # useblacksmith/rust-cache@v3

    # cargo tools
    - uses: baptiste0928/cargo-install@v3
      with:
        crate: txtpp
